### ISSUE TITLE
Hide floor plane when product placed

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/DreamBuilder#11]
Let's toggle the Show plane state off when the pergola is "placed".  It's no longer needed and looks ugly.

Speaking of which: is there a prettier graphic for the plane?  Like a plane of + signs or other?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I Hide the plane once the object placed. 
Do you have any reference of prettier graphic for plane? I will try to implement plane with + signs.

**Comment by tedbarnett** [comment]
Let's leave it green for now if there are no other easy-to-use pattern options built in to ARKit.
