### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/DreamBuilder#17]
Let's move to a one-screen interface where the camera view is the main view. All other features (choosing product model, selecting base color and louver color, opening louver, lights on/off) are on buttons that toggle on/off with the menu button. 

When app opens, go to the camera view with a single button in center of screen reading "set ground". Tapping button starts floor-find process.  When floor is found, current model (eg our black 2-post Pergola X) appears on the screen at REAL size (should be 12' deep and 20' wide). 

User can rotate and move the Pergola (along the ground) but not pinch-zoom scale it. User can modify width with width slider. 

User can change the model (eg to the "4 post" model) and it's replaced on-screen exactly where the prior model was. No need to re-find the floor!

**Comment by tedbarnett** [comment]
One more button:
- Width slider (widens model in the X dimension from 12ft to 24ft). Does not scale up height or depth. Model should always have a 12ft depth as it does by default. 

FYI: our default base pergola model is 20ft in width with a 12ft "depth"

**Comment by tedbarnett** [comment]
For the color pop-ups:
- the default base color is black, louvers white
- want to add "white" as an option for base colors and black for louver color
- can we change the material of that object to white or other colors?

**Comment by bhautikpatoliya004** [comment]
@tedbarnett 
I've some questions regarding your above descriptions, could you please explain in detail?

1) Model pop/up (two options: 2 post, 4 post)
--> What is 2 post and 4 post? Will you provide this?


2) Louver slider (like current: should go from 0 to 170 degrees in 10 degree increments. Center at 90 degrees - blades are vertical)
--> I don't get understood this, please explain in details as the animation is developed inside the .usdz model and I'm controlling speed using slider currently. So, what change I need to do?


3) Width slider (widens model in the X dimension from 12ft to 24ft). Does not scale up height or depth. Model should always have a 12ft depth as it does by default.
FYI: our default base pergola model is 20ft in width with a 12ft "depth"
--> I Understood little bit but could you explain details?

**Comment by tedbarnett** [comment]
1) We will make a  new 4-post model.  Just have the "2 post" now.  Make both buttons open the same one for now.  don't show the other 4 buttons (Pan, etc.) anymore: just the ones mentioned above.
2) Ideally it's simply moving to a specific frame of the animation as the slider is adjusted. Is that possible.
3) This just means scaling the model in the X dimension (stretching it horizontally).  Eventually we will make this more accurate (i.e. add louvers and modify the model as it gets wider).  For now, just stretch it.

**Comment by ChiefSeattle** [comment]
Moving model around on screen is difficult when enlarged

**Comment by ChiefSeattle** [comment]
Only need Pergola X on main menu.

We can add 2 model choices:

1. Freestanding (4 posts)
2. House-attached (2 posts)

**Comment by tedbarnett** [comment]
I'll let @ChiefSeattle close these issues when he gets the new build. By tomorrow.
