### ISSUE TITLE
Too many colors

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/DreamBuilder#21]
Changing the beam colors is awesome but we have too many color choices. Hot pink?  For now reduce it to black, white, silver, grey, brown. 

@ChiefSeattle will confirm actual color list. 

![image](https://github.com/user-attachments/assets/2cc4adaf-8c40-4448-93da-12a2109a184e)

**Comment by ChiefSeattle** [comment]
Frame colors:

![image](https://github.com/user-attachments/assets/122fc72c-050e-4493-9bf9-a186c9e4c91e)

Louver colors:

![image](https://github.com/user-attachments/assets/f85deb97-8115-48d6-af26-7fa18a48e469)
