### ISSUE TITLE
Build Blender model of basic 2-post pergola (with open and closed versions)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/DreamBuilder#4]
We need to generate a scale USDZ model of a typical "pergola" like the images pasted below.  We should start with a Blender (or Maya if easier) model that can be used to export the USDZ.  We need to be able to show the pergola in 2 states: 
1) louvers closed (see photo 01 and 02 below)
2) louvers open (see photo 02 below)

We will start with the "Pivot 6" model, as described here: https://struxure.com/products/pivot-6/

Its exterior dimensions are:
- 24' wide
- 12' tall
- 8' deep
- all beams are 8" in thickness (and square in cross-section)

![Pergola Dimensions](https://github.com/user-attachments/assets/2796ea96-8326-4ab5-aab9-961391f06c61)

As in the photos below, it will have a total of 45 louvers (the horizontal bars that can be turned to block the sun/rain).  There are 15 louvers in each section of of the top.

The cross bars between each of the 3 sections should have 3 recessed lights to which we can attach emissive "light" materials.  See Photo 05 below.

Photo 01 (standard small Pergola model: louvers closed)
![image](https://github.com/user-attachments/assets/ec35b2e9-c767-4d95-89ca-8f9cdf088eff)

Photo 02 (same standard small Pergola model: louvers closed)
![image](https://github.com/user-attachments/assets/ec35b2e9-c767-4d95-89ca-8f9cdf088eff)

Photo 03 (louvers open, white material)
![image](https://github.com/user-attachments/assets/ca49b1cc-7e43-4e23-adea-3abdb8d2aa9c)

Photo 04 (cross-sections of louver)
![image](https://github.com/user-attachments/assets/c4240908-025a-4598-9bbc-94d0f48e5440)

![image](https://github.com/user-attachments/assets/42aaf357-98dc-48b9-a26f-2ecb403e0d03)

Photo 05 (light bar with lights)
![image](https://github.com/user-attachments/assets/8a96ba90-0e4d-459a-9a09-d15882ef91f6)

Photo 06 (deeper, larger example)
![image](https://github.com/user-attachments/assets/26d00c37-def5-4928-97af-3f2dbd3621bb)

More details available here: https://github.com/tedbarnett/DreamBuilder/issues/3
 - But note that we do not need to replicate every screw and bolt on the product: just a "realistic" looking model
 - The louvers should be curved as they are in the image above, and can be rotated to open

Future modifications:
 - Because each pergola is a custom installation, the dimensions and colors of the product can vary
 - Make sure the materials can be changed to black, white, dark grey (and others in the future)
 - Make sure we can someday make the model wider or taller
 - The model can someday be made "deeper" by using longer louvers (as in photo 03 below)

**Comment by tedbarnett** [comment]
More data can be found here, but it's probably more detail than we need!  
https://struxure.com/for-pros/drawing-3d-models/

**Comment by ChiefSeattle** [comment]
The overall dimensions should be:

12' deep
20' long
9' tall posts - 8"x8" square posts. 
The 8" beam all around sits on top of the 9' posts.

Note: The project photos represent different custom sizes.  The most common overall size and a good starting point for the model is: 12' x 20'

**Comment by tedbarnett** [comment]
@ChiefSeattle check out these first-draft models from Alvin:

Closed:
![image](https://github.com/user-attachments/assets/5dfc942c-e342-4abf-ae92-6f183480f37a)

Open:
![image](https://github.com/user-attachments/assets/a7bc3baa-cf5d-4e85-a5f1-cb5410c0ba76)

**Comment by ChiefSeattle** [comment]
Hi Ted.  That's a very close example of the product and should work.  I have had some 8' deep pergolas, but the dimensions I was suggesting in an earlier comment are:

The overall dimensions should be:
12' deep (from house-side out)
20' long (overall length mounted to house)
9' tall posts - 8"x8" square posts.
The 8" tall beam (the roof component)sits on top of the 9' posts.

Note: The project photos I uploaded represent different custom sizes. The **most common overall size** and a good starting point for the model is: 12' x 20'

Here's a link to the design details: https://github.com/user-attachments/files/16972967/Pergola.design.drawing.details.pdf

Note: For this project, the posts should be at the corners rather than offset/cantilevered.  Majority of orders have posts at the corners.

**Comment by ChiefSeattle** [comment]
Here's another example of a 12x20 mounted to a roof on a home.  The 2 post design often works as a house-mounted or roof-mounted application.  The model you're making should be useful to show either customer how the design could look on their home. 

Note: if there's a way to adjust the post length to increase or decrease pergola height +/- 1foot in the app that would help adjust for different home designs.

![image](https://github.com/user-attachments/assets/1348f25a-aed4-430f-b15e-522da85c11e5)

![image](https://github.com/user-attachments/assets/74e97de5-8fcc-4fd6-a427-016404bd9bee)

![image](https://github.com/user-attachments/assets/82e300d4-b7c9-4aa6-8eeb-2bce3803f344)

**Comment by ChiefSeattle** [comment]
![image](https://github.com/user-attachments/assets/2e4a834b-4953-4b56-a225-7e2681dd1717)

![image](https://github.com/user-attachments/assets/c4d6adbd-a886-4cff-84f3-b9bea46c9281)

![image](https://github.com/user-attachments/assets/00e93c30-7cec-49ea-a88b-fa4cb8f2b7f8)

**Comment by ChiefSeattle** [comment]
Here's a link to a 'visualizer' on the StruXure website.
The 12x20 will be more useful.  Having the ability to select different colors for our app would be great, if possible.  The extra decorative elements are not necessary.

https://struxure.com/products/pivot-6/pivot6-visualizer/

**Comment by ChiefSeattle** [comment]
Product color for initial model:

Bronze frame and posts
Beige louvers

Lighting:

**Downlighting**
Adding a 'light bar' - the beam across the middle with 3 warm white down lights, under the louvers is a nice option. We can include that in the model.  Maybe a way to 'hide' it will help customers see what it looks like with or without it.

**RGB accent lighting**
Ambient rope lighting for the interior perimeter of the ceiling.  We offer a remote control that allows customers to change the light color.  A single dark blue glow like the photo below will help customer's visualize this lighting option. Maybe a way to 'hide' it will help customers see what it looks like with or without it.



![image](https://github.com/user-attachments/assets/da8fc278-d54c-432d-9655-4302289c014e)![image](https://github.com/user-attachments/assets/0e9a7459-d16e-4e32-b1e8-7711ea6d7471)

**Comment by tantayota** [comment]
hello @tedbarnett @ChiefSeattle here is my detailed version of the 2 post pergola. I created a parts by parts 3d model of Post, Beam, Gutter and louvers and assemble as one. each part can be edited to desired length and width and can reduce louvers or add more without modifying animation. I can animate the open and close which is a great feature if we will export it to usdz. 

![pergola1](https://github.com/user-attachments/assets/9273bb06-1da6-4fdd-817c-281a412bc7fd)
![pergola2](https://github.com/user-attachments/assets/e3382f93-ee2a-4366-97ca-83986e72ef71)
![pergola3](https://github.com/user-attachments/assets/397d2541-cd3f-4de7-9556-02d98e3937cb)
![pergola4](https://github.com/user-attachments/assets/5e0b0c1a-59fa-41a5-b36f-9872cdad9a81)
![pergolaRender](https://github.com/user-attachments/assets/48f2a3c7-74a7-4446-aff8-a3b8f6f5db99)

I also created a quick video rendering so we can visualize more. (note. i made a mistake which is the pergola in this video is 24' long but since the 3d models i created is easy to adjust. i already modified it and placed 20' long pergola). 

https://github.com/user-attachments/assets/ee503911-e4e5-4111-b6da-d0678bf06eed

**Comment by ChiefSeattle** [comment]
Looks great!  
Please make the colored accent lighting brighter on the ceiling. Also, please illuminate the 3 downlight fixtures on the light bar.

**Comment by tedbarnett** [comment]
@tantayota Note Chris' latest info on the exact dimensions of the pergola (see above)

**Comment by tedbarnett** [comment]
@ChiefSeattle Please clarify dimensions one more time.  I see a 9' height and an 8' height in the notes above.  I am assuming we should use:
- Height: 9 ft (2.7m)
- Width: 20 ft (6.1m)
- Depth: 12 ft (3.7m)
-

**Comment by ChiefSeattle** [comment]
The 9 foot ceiling height is correct.

**Comment by ChiefSeattle** [comment]
Re: accent lighting - if different colors can be selected that would be nice option to have - basic Red / Green / Blue or a color wheel.

**Comment by tantayota** [comment]
@tedbarnett @ChiefSeattle the current size of the pergola is 

Height: 9 ft (2.7m)
Width: 20 ft (6.1m)
Depth: 12 ft (3.7m)

also in blender i can just select all the objects and just resize the pergola to the size we want in no time.

**Comment by tantayota** [comment]
as per the color of the lights. i am still looking into it since what we want is USDZ file and we want to include 3d objects, Animations of Open and close of louvers and lightings. I will try to Export it now on USDZ and import into IOS, IpadOS and macOS and check what is usable and what it looks like.

**Comment by ChiefSeattle** [comment]
If the lights need to be handled separately from the modeling, no problem :)

**Comment by tantayota** [comment]
Okay cool. I will look into the USDZ now for the best settings.

**Comment by ChiefSeattle** [comment]
Would like to select different colors for the pergola in the app?  Ie. All the same color or 1 color for frame and post and a different color for the louvers.

**Comment by tantayota** [comment]
I am also looking in that area. In blender i can easily do that. Im just replacing the material applied to the specific parts. 

![image](https://github.com/user-attachments/assets/88c55247-873a-4438-87b3-08229120c47e)

**Comment by ChiefSeattle** [comment]
Here's a basic UI configuration image example for the pergola.  The model colors can be selected, along with lighting options.

![image](https://github.com/user-attachments/assets/b446b0cd-c4b3-4063-88a8-2aa5f593c361)

**Comment by tantayota** [comment]
Hello @tedbarnett @ChiefSeattle I have tested in IOS and Ipad the Pergola 3d model that i created using blender which is exported as a USDZ. But the result i am getting is just the 3d model with looping animation and has no lightings .

![IMG_0380](https://github.com/user-attachments/assets/6e1d7c6e-ef52-4ae1-b7f8-938aacc6b484)

Here is the link for the blender file and a USDZ file.(Just ignore the USDZ file size for now ill try to reduce it and will use just for testings)

https://drive.google.com/drive/folders/1eoQElAKu71yDMFqORJ9CmL4Q6Ob8cs7D?usp=sharing

Question. How should we use this 3d model? Are you guys developing an APP that can view this 3d models change its materials and state? this is important because that is the basis of how I should create and prepare 3d Objects.

**Comment by ChiefSeattle** [comment]
We are developing an app to view the model in live AR view on the side of buildings.  We would like to change model colors and sizes

**Comment by tedbarnett** [comment]
The app is roughly described on the home page of this repo.  
https://github.com/tedbarnett/DreamBuilder/

**Comment by bhautikpatoliya004** [comment]
@tedbarnett @tantayota I tried Apple 3D assets from their samples, and they work smoothly in our application. Their 3D objects are in .scn(Scene) file format. I used the .usdz file of pergola provided here in the Google Drive link but it's not working fine as well as it's not showing in the correct position.

Here is the link for the screen recording: https://drive.google.com/file/d/1U3Sk29LOInPLRg4EpPqdhkP0vAvQnyj2/view?usp=share_link

Is there any way to export the .scn file from Blender? Also, I tried converting .usdz to .scn but still, it's not showing correctly in the app and the position changed. Once this issues is resolved than there will be no issue of Pergola moves when scaling and others.

**Comment by tantayota** [comment]
@bhautikpatoliya004  Hello. this might be a common problem. Different 3d software has their own preferred AXIS in blender we use X axis for horizontal  , Y axis for Forward and Z axis for Vertical . we used this axis also to rotate some objects. as the 3d viewer you are using in the app it might be X for Horizontal, Y for Vertical and Z for Forward. can you try this two USDZ files(PERGOLA_12x20x9_Y-UP and PERGOLA_12x20x9_Z-UP)? thanks 
![image](https://github.com/user-attachments/assets/87d74eee-8c54-45fc-875a-be687c44aa10)

**Comment by bhautikpatoliya004** [comment]
@tantayota I tried both USDZ files(PERGOLA_12x20x9_Y-UP and PERGOLA_12x20x9_Z-UP) from Google Drive.
Here is the result of Y-UP: https://drive.google.com/file/d/1C4X7F0CMCKwkZmZWENgTtTujCmMnY6Mk/view?usp=share_link

Here is the result of Z-UP: https://drive.google.com/file/d/1dSF-wfJ83-WikXLThLGrbDXreaHs5RsB/view?usp=share_link


From the above result, it seems that Y-UP is showing correctly, but it's not sticking to the ground and is showing above the ground. Is there any way to fix it?

**Comment by tantayota** [comment]
@bhautikpatoliya004 is there any a way i can test it my self? i think not sticking to the ground is a different issue. This problems might be a way to create a pipeline that will work from importing blender files to the app. in this screen shot is located the pivot point of the whole 3d model (pivot point represented by 3D gizmo). 
![image](https://github.com/user-attachments/assets/58796451-814c-4e12-b058-66aa654548bd)

**Comment by bhautikpatoliya004** [comment]
@tantayota  Do you app source code? Or want to install app in your iOS device?

**Comment by tantayota** [comment]
@bhautikpatoliya004 I just want to test the app. is source code needed to add 3d models to the app or there are import option inside the app after installation?

**Comment by bhautikpatoliya004** [comment]
@tantayota Ted already invited you to the iOS app repo. You will need to install Xcode and run the code. 

After installing Xcode and getting the Dreambuilder app code, please open the below file.

<img width="237" alt="Screenshot 2024-11-10 at 10 04 54 AM" src="https://github.com/user-attachments/assets/742f159e-b809-4a81-9ff6-accd3b5d16e7">

You need to replace this .usdz file with newly exported .usdz file from Blender(Please see below screenshot).
<img width="1177" alt="Screenshot 2024-11-10 at 10 03 40 AM" src="https://github.com/user-attachments/assets/656f9299-1cc2-4380-8071-41907a600a0f">

You must install a certificate and profile to run it on your iPhone.

**Comment by tantayota** [comment]
Hello @bhautikpatoliya004 I followed your instruction and found a way to run on my iphone but I am getting this error. Any Idea what is happening? Thanks

<img width="1135" alt="Screenshot 2024-11-12 at 7 51 28 PM" src="https://github.com/user-attachments/assets/a2c13384-fabf-4c8b-846d-90a62b2739e0">

I

**Comment by bhautikpatoliya004** [comment]
@tantayota Did you add file with same name as before? And which iOS version is installed on your iPhone 11?

**Comment by tantayota** [comment]
@bhautikpatoliya004 I did not change the file yet. I just want to test if the app and the pergola is working before i proceed on replacing the 3d file. and the iphone has IOS 18.0.1

**Comment by bhautikpatoliya004** [comment]
@tantayota think this error messages indicate a compatibility issue related to either device-specific hardware limitations or differences in iOS support for USDZ handling across devices.

**Comment by tedbarnett** [comment]
@bhautikpatoliya004 Would it help to try converting the properly-setup Apple USDZ demo files into Blender to see how they set up their pivots?  I can do that here if you post the USDZ files.

**Comment by tedbarnett** [comment]
Moved to new issue #22
